---
slug: tau_manifesto_article
filename: tau_manifesto_article
title: The Tau Manifesto
subtitle: Change me
description: Change me.
author: Author Name
copyright: 2015
uuid: 5dc383dd-c6d3-47db-a97a-486a689a792b
pdf_preview_page_range: 1..30
epub_mobi_preview_chapter_range: 0..1
