---
chapter:
  word: Capítulo
  order: standard     # Use 'reverse' to change 'Chapter 1' to '1 Chapter'
section: Seção
table: Tabela
figure: Figura
fig: Fig
aside: Quadro
listing: Listagem
equation: Equação
eq: Eq
frontmatter: Introdução
contents: Conteúdo
