---
prices:
  -
    code: ebooks
    name: "The Tau Manifesto and Tau Talk"
    description:
      |
        * The Tau Manifesto in EPUB, MOBI, and PDF formats
        * Downloadable videos of the Tau Talk, both short and long versions
        * Priority announcements of tau-related merchandise, news, and events
    media:
      - ebooks_videos
    price: 900

authors:
  -
    name: "Michael Hartl"
    gravatar_email: "michael@michaelhartl.com"
    contact_email: "tauday@michaelhartl.com"
    contact_twitter: "@tauday"
    contact_fb: "http://facebook.com/mhartl"
    bio:
      |
        As founder of [Tau Day](http://tauday.com/) and
        author of [*The Tau Manifesto*](http://tauday.com/tau-manifesto),
        Michael Hartl is a leader in the international fight against &pi;
        oppression. He is
        also the creator of the [Ruby on Rails Tutorial](http://www.railstutorial.org/),
        a book and screencast series that is
        one of the leading introductions to web development. Michael is a
        graduate of [Harvard College](http://college.harvard.edu/), has a
        [Ph.D. in Physics](http://thesis.library.caltech.edu/1940/) from [Caltech](http://caltech.edu/), and is an alumnus
        of the [Y&nbsp;Combinator](http://ycombinator.com/) entrepreneur program.

faq:
  -
    question: "Question 1 text"
    answer: "Answer 1 text"

  -
    question: "Question 2 text"
    answer: "Answer 2 text"

testimonials:
  -
    name: "Joyce Tipping"
    title: "ancestral gourmet, intellectual nomad, wife & mother"
    image: /images/joyce_tipping.jpg
    text: "Hooray for tau! This breathes new life into my trigonometry."

  -
    name: "Person 2"
    title: "Person 2 Title"
    gravatar_email: "info@softcover.io"
    text: "Testimonial 2 text"

marketing_content: ''

repo_url: ''
contact_email: ''
hide_custom_domain_footer: false
