---
prices:
  -
    code: ebooks
    name: "The Tau Manifesto and Tau Talk"
    description:
      |
        * The Tau Manifesto in EPUB, MOBI, and PDF formats
        * Downloadable videos of the Tau Talk, both short and long versions
        * Priority announcements of tau-related merchandise, news, and events
    media:
      - ebooks_videos
    price: 900

authors:
  -
    name: "Michael Hartl"
    gravatar_email: "michael@michaelhartl.com"
    contact_email: "tauday@michaelhartl.com"
    contact_twitter: "@tauday"
    contact_fb: "http://facebook.com/mhartl"
    bio:
      |
        As founder of [Tau Day](http://tauday.com/) and
        author of [*The Tau Manifesto*](http://tauday.com/tau-manifesto),
        Michael Hartl is a leader in the international fight against &pi;
        oppression. He is
        also the creator of the [Ruby on Rails Tutorial](http://www.railstutorial.org/),
        a book and screencast series that is
        one of the leading introductions to web development. Michael is a
        graduate of [Harvard College](http://college.harvard.edu/), has a
        [Ph.D. in Physics](http://thesis.library.caltech.edu/1940/) from [Caltech](http://caltech.edu/), and is an alumnus
        of the [Y&nbsp;Combinator](http://ycombinator.com/) entrepreneur program.

testimonials:
  -
    name: "Joyce Tipping"
    title: "[@joycetipping](https://twitter.com/joycetipping/status/17302692133)"
    image: /images/joyce_tipping.jpg
    text: "Hooray for tau! This breathes new life into my trigonometry."

  -
    name: "Charles D. Aylward"
    title: "[@cdaylward](https://twitter.com/cdaylward/status/17552758427)"
    image: /images/cdalyward.jpg
    text: "That sound? It's my mind blowing. Childhood suspicions confirmed. The circle constant is broken. Switching to τ immediately."

  -
    name: "Scott Conley"
    title: "[@14to9](https://twitter.com/14to9/status/17277113296)"
    image: /images/14to9.png
    text: "Do not circles deserve first-class quadratic recognition? Let us throw off the yoke of ignorant π oppression!"

  -
    name: "David Vrensk"
    title: "[@dvrensk](https://twitter.com/dvrensk/status/17360671177)"
    image: /images/dvrensk.jpg
    text: "Oh no, I missed Tau Day!"


marketing_content: ''

repo_url: ''
contact_email: ''
hide_custom_domain_footer: false
